import time as ti
print("Welcome to your virtual shower!")
ti.sleep(2)
print("This is a simulation of a IRL shower.")
ti.sleep(1)
print("Please wait while we load the frameworks.")
print("This program was developed by Jordan Jordanov. Contact me at: jordanovdanny@gmail.com")
ti.sleep(2)
print("This program is developed in Python 3 with the Thonny IDE.")
ti.sleep(6)
dev_mode = input("")
if dev_mode == "09102009":
    print("Skipping all unneeded prints")
else:
    print("Downloading Framework 1.6.7...")
    ti.sleep(1)
    print("Progress 1%")
    ti.sleep(1)
    print("Progress 2%")
    ti.sleep(1)
    print("Progress 3%")
    ti.sleep(1)
    print("Progress 4%")
    ti.sleep(1)
    print("Progress 5%")
    ti.sleep(1)
    print("Progress 6%")
    ti.sleep(1)
    print("Progress 7%")
    ti.sleep(1)
    print("Progress 8%")
    ti.sleep(1)
    print("Progress 9%")
    ti.sleep(1)
    print("Progress 10%")
    ti.sleep(3)
    print("Progress 11%")
    ti.sleep(0.5)
    print("Progress 12%")
    ti.sleep(0.5)
    print("Progress 13%")
    ti.sleep(0.5)
    print("Progress 14%")
    ti.sleep(0.5)
    print("Progress 15%")
    ti.sleep(3)
    print("Progress 16%")
    ti.sleep(0.5)
    print("Progress 17%")
    ti.sleep(0.5)
    print("Progress 18%")
    ti.sleep(0.5)
    print("Progress 19%")
    ti.sleep(0.5)
    print("Progress 20%")
    ti.sleep(1)
    print("Progress 21%")
    ti.sleep(1)
    print("Progress 22%")
    ti.sleep(1)
    print("Progress 23%")
    ti.sleep(1)
    print("Progress 24%")
    ti.sleep(1)
    print("Progress 25%")
    ti.sleep(1)
    print("Progress 26%")
    ti.sleep(1)
    print("Progress 27%")
    ti.sleep(1)
    print("Progress 28%")
    ti.sleep(1)
    print("Progress 29%")
    ti.sleep(1)
    print("Progress 30%")
    ti.sleep(0.5)
ti.sleep(5)
print("Downloaded important files. Other files are not needed.")
print("Please enter your name: ")
users_name = input("")

if users_name == "DangerD4N1":
    print("Hello, developer! Welcome back to your program!")
else:
    print("Hello, " + users_name + "! Welcome again to your Virtual Shower!")
print("Curently your shower is turned off. Whould you like to turn the shower off? yes/no. (Program is case-sentative)")
shower_on_off = input("")
if shower_on_off == "yes":
    print("Okay...")
    ti.sleep(2)
    print("Shower is on!")
    print("What Temputure whould you like the to be at [Celcius]? (Example: 24, 30, 20, etc.)")
    temp = input("")
    a_temp = temp + "°C"
    ti.sleep(2)
    print("Setting temputure to " + a_temp + "...")
    ti.sleep(2)
    print("Temuture set to " + a_temp + ".")
    print("Enjoy your shower!")
if shower_on_off == "yno":
    print("Okay...")
    ti.sleep(2)
    print("I guess this is our goodbye... :(")
    ti.sleep(1)
    print("Goodbye... :(")